site_name: Lakehouse Engine
site_description: A Spark framework serving as the engine for several lakehouse algorithms and data flows.
site_url: https://adidas.github.io/lakehouse-engine-docs

theme:
  name: "material"
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: "default"
      primary: "light blue"
      accent: "pink"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "pink"
      accent: "red"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  # favicon: statics/images/favicon.ico
  # logo: statics/images/logo-white.svg
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.code.select
    - navigation.indexes
    - navigation.path
    - navigation.tabs

repo_name: adidas/lakehouse-engine
repo_url: https://github.com/adidas/lakehouse-engine
edit_uri: ""
plugins:
  - search
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
      trim: false
  - markdownextradata:
      data: data

nav:
  - Introduction: "index.md"
  - Contributing: "contributing.md"
  - Terms and Conditions: "terms-and-conditions.md"
  - Release Notes: "release-notes.md"
markdown_extensions:
  - toc:
      permalink: true
  - mdx_include:
      base_path: docs
  - admonition
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  alternate:
    - link: /
      name: English
      lang: en
