pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '30'))
        timeout(time: 2, unit: 'HOURS')
        disableConcurrentBuilds()
        skipDefaultCheckout(true)
        ansiColor('xterm')
        timestamps()
    }

    agent {
        node {
            label 'lakehouse_base'
        }
    }

    environment {
        VERSION = env.BRANCH_NAME.replaceAll("[/-]", "_").toLowerCase()
        GIT_CREDENTIALS_ID = "git-lakehouse-cicd"
    }

    stages {
        stage('cleanup workspace') {
            steps {
                cleanWs(disableDeferredWipeout: true, deleteDirs: true)
            }
        }

        stage('Clone') {
            steps {
                retry(3) {
                    script {
                        checkout([
                                $class           : 'GitSCM',
                                branches         : scm.branches,
                                userRemoteConfigs: scm.userRemoteConfigs,
                                // when using Sonar Quality Gate, a full clone is required
                                extensions: [[$class: 'CloneOption', shallow: false]]
                        ])
                    }
                }
            }
        }

        stage('Build Image') {
            steps {
                sh 'make build-image version=$VERSION'
            }
        }

        stage('Build whl') {
            steps {
                sh 'make build version=$VERSION'
            }
        }

        stage('Create Docs') {
            steps {
                sh 'make docs version=$VERSION'
            }
        }

        stage('Parallel') {
            parallel {
                stage('Lint') {
                    steps {
                        sh 'make lint version=$VERSION'
                    }
                }

                stage('Test Security') {
                    steps {
                        sh 'make test-security version=$VERSION'
                    }
                }

                stage('Audit Dependency Safety'){
                    steps{
                        catchError(message: "${STAGE_NAME} is unstable", buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                            sh 'make audit-dep-safety version=$VERSION'
                        }
                    }
                }

                stage('Test dependencies') {
                    steps {
                        sh 'make test-deps version=$VERSION'
                    }
                }
            }
        }

        stage('Test Local') {
            steps {
                sh 'make test-local version=$VERSION'
            }
        }

        stage('Test Connect') {
            steps {
                sh 'make test-spark-connect version=$VERSION'
            }
        }

        stage ('Combine Coverage') {
            steps {
                sh 'make combine-coverage version=$VERSION'
            }
        }

        stage('Sonar') {
            steps {
                withSonarQubeEnv('COMMUNITY-PRD') {
                    script {
                        def scanner_home = tool 'SonarQube 7.0'
                        def version_number = sh script: "make print-variable var=version_number", returnStdout: true

                        sh "${scanner_home}/bin/sonar-scanner -Dsonar.projectVersion=${version_number}"
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'artefacts/docs/**/*'
            archiveArtifacts artifacts: 'artefacts/*.json'
            junit 'artefacts/tests.xml'
            recordCoverage(tools: [[parser: 'COBERTURA', pattern: "artefacts/coverage.xml"]])
        }
    }
}